In [59]:
import yfinance as yf
import datetime as dt
import pandas as pd

In [57]:
data_inicio = dt.date(2020, 1, 1)
data_final = dt.date(2025, 8, 14)

In [ ]:
path = 'https://raw.githubusercontent.com/GunzLauncher/portfolios_investment_analysis/refs/heads/main/acoes-listadas-b3.csv?token=GHSAT0AAAAAADIX7Z6DYYYATUJOLCTYRNNO2E6XBSA'
ativos = pd.read_csv(path, sep=',')
todos_ativos = [f'{s}.SA' for s in ativos['Ticker']]

In [73]:

df_ativos = yf.download(todos_ativos, data_inicio, data_final)
colunas_remover = ['Open', 'High', 'Low', 'Volume', 'Adj Close']
df_ativos.drop(columns=colunas_remover, inplace=True)
precos_fechamento_ativos = df_ativos.droplevel(0, axis=1)
precos_fechamento_ativos.head()

C:\Users\lgdmt\AppData\Local\Temp\ipykernel_10064\334712105.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_ativos = yf.download(todos_ativos, data_inicio, data_final)
[*********************100%***********************]  390 of 390 completed

4 Failed downloads:
['LUPA11.SA', 'PINE11.SA', 'AZEV11.SA', 'AMAR11.SA']: YFTzMissingError('possibly delisted; no timezone found')

Ticker,AALR3.SA,ABCB4.SA,ABEV3.SA,AERI3.SA,AFLT3.SA,AGRO3.SA,AGXY3.SA,ALLD3.SA,ALOS3.SA,ALPA3.SA,...,VVEO3.SA,WEGE3.SA,WEST3.SA,WHRL3.SA,WHRL4.SA,WIZC3.SA,WLMM3.SA,WLMM4.SA,YDUQ3.SA,ZAMP3.SA
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,18.843966,13.585620,15.051882,NaN,8.336596,12.025983,NaN,NaN,43.243900,26.035538,...,NaN,16.168983,NaN,6.085058,6.173802,9.727118,10.572206,11.554443,41.797306,17.289736
2020-01-03,18.843966,13.886777,14.840214,NaN,8.329174,12.150929,NaN,NaN,44.463135,26.414415,...,NaN,15.962514,NaN,6.030293,6.071606,9.727118,10.572206,12.055685,40.921127,16.990776
2020-01-06,18.834047,13.799780,14.910770,NaN,8.321751,12.157175,NaN,NaN,44.160492,25.899532,...,NaN,16.003809,NaN,5.963357,6.029527,10.255839,11.007734,12.781617,41.707901,17.170153
2020-01-07,18.784458,13.625775,14.942129,NaN,8.284633,12.119691,NaN,NaN,43.641674,25.889818,...,NaN,16.127695,NaN,5.835569,5.843169,10.825233,13.860008,16.411287,40.930065,17.279770
2020-01-08,18.814211,13.585620,14.871572,NaN,8.269786,11.994747,NaN,NaN,44.964664,26.006395,...,NaN,15.517456,NaN,5.847740,5.975422,10.099936,13.791689,16.368073,40.688667,17.170153