In [1]:
import yfinance as yf
import datetime as dt
import pandas as pd

In [2]:
data_inicio = dt.date(2015, 1, 1)
data_final = dt.date(2025, 8, 14)

In [3]:
path = 'https://raw.githubusercontent.com/GunzLauncher/portfolios_investment_analysis/refs/heads/main/acoes-listadas-b3.csv'
ativos = pd.read_csv(path, sep=',')
todos_ativos = [f'{s}.SA' for s in ativos['Ticker']]
selecao_ativos = ['WEGE3.SA', 'PETR4.SA', 'VALE3.SA']

In [5]:

precos_ativos = yf.download(todos_ativos, data_inicio, data_final)
colunas_remover = ['Close', 'High', 'Low', 'Volume']
precos_ativos.drop(columns=colunas_remover, inplace=True)
precos_ativos

C:\Users\lgdmt\AppData\Local\Temp\ipykernel_9952\2999608417.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  precos_ativos = yf.download(todos_ativos, data_inicio, data_final)
[*********************100%***********************]  390 of 390 completed

4 Failed downloads:
['LUPA11.SA', 'AMAR11.SA', 'AZEV11.SA', 'PINE11.SA']: YFTzMissingError('possibly delisted; no timezone found')

Price      Adj Close                                   Open             \
Ticker     AMAR11.SA AZEV11.SA LUPA11.SA PINE11.SA AALR3.SA   ABCB4.SA
Date
2015-01-02       NaN       NaN       NaN       NaN      NaN   4.592240
2015-01-05       NaN       NaN       NaN       NaN      NaN   4.513617
2015-01-06       NaN       NaN       NaN       NaN      NaN   4.449290
2015-01-07       NaN       NaN       NaN       NaN      NaN   4.367093
2015-01-08       NaN       NaN       NaN       NaN      NaN   4.292045
...              ...       ...       ...       ...      ...        ...
2025-08-07       NaN       NaN       NaN       NaN     5.00  21.540001
2025-08-08       NaN       NaN       NaN       NaN     5.24  21.639999
2025-08-11       NaN       NaN       NaN       NaN     5.21  21.700001
2025-08-12       NaN       NaN       NaN       NaN     5.04  21.680000
2025-08-13       NaN       NaN       NaN       NaN     5.25  22.090000

Price                                                ...                      \
Ticker       ABEV3.SA AERI3.SA  AFLT3.SA   AGRO3.SA  ... VVEO3.SA   WEGE3.SA
Date                                                 ...
2015-01-02  10.279516      NaN  1.418221   4.263891  ...      NaN   4.914575
2015-01-05  10.133030      NaN  1.418221   4.147470  ...      NaN   4.948082
2015-01-06  10.018390      NaN  1.418221   4.249339  ...      NaN   4.925743
2015-01-07  10.406895      NaN  1.418221   4.283295  ...      NaN   4.868300
2015-01-08  11.108167      NaN  1.418221   4.268741  ...      NaN   4.852344
...               ...      ...       ...        ...  ...      ...        ...
2025-08-07  12.510000     4.34  7.380000  20.370001  ...     1.10  38.180000
2025-08-08  12.550000     4.37  7.380000  20.360001  ...     1.08  38.930000
2025-08-11  12.370000     4.37  7.380000  20.270000  ...     1.05  38.130001
2025-08-12  12.380000     4.30  7.380000  20.290001  ...     1.03  37.650002
2025-08-13  12.230000     4.34  7.380000  20.299999  ...     1.04  36.619999

Price                                                                 \
Ticker     WEST3.SA  WHRL3.SA  WHRL4.SA WIZC3.SA WLMM3.SA   WLMM4.SA
Date
2015-01-02      NaN  1.854085  1.749019      NaN      NaN  10.472371
2015-01-05      NaN  1.849450  1.686234      NaN      NaN  10.472371
2015-01-06      NaN  1.691853  1.623448      NaN      NaN  10.472371
2015-01-07      NaN  1.807733  1.556179      NaN      NaN  10.472371
2015-01-08      NaN  1.807733  1.592056      NaN      NaN  10.472371
...             ...       ...       ...      ...      ...        ...
2025-08-07     4.50  4.160000  4.470000     7.55    23.99  20.500000
2025-08-08     4.50  4.280000  4.400000     7.90    23.99  20.500000
2025-08-11     4.65  4.330000  4.680000     8.15    23.99  20.549999
2025-08-12     4.91  4.260000  4.770000     8.20    23.99  20.200001
2025-08-13     4.63  4.210000  4.720000     8.06    23.99  20.389999

Price
Ticker       YDUQ3.SA ZAMP3.SA
Date
2015-01-02  16.829828      NaN
2015-01-05  15.287096      NaN
2015-01-06  14.648966      NaN
2015-01-07  14.130045      NaN
2015-01-08  13.365691      NaN
...               ...      ...
2025-08-07  13.400000     3.46
2025-08-08  13.530000     3.47
2025-08-11  13.450000     3.47
2025-08-12  13.380000     3.47
2025-08-13  13.380000     3.49

[2641 rows x 394 columns]